version: '3.8'

services:
  # MongoDB Database (Development)
  mongodb:
    image: mongo:7.0
    container_name: vaccine-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: vaccine_management
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - vaccine-dev-network

  # Backend API (Development with hot reload)
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: vaccine-backend-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/vaccine_management?authSource=admin
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - vaccine-dev-network
    command: npm run dev

volumes:
  mongodb_dev_data:

networks:
  vaccine-dev-network:
    driver: bridge
